### ISSUE TITLE
problem with converted caQtDM screen

### ISSUE THREAD

**Issue by prjemian** [epics-modules/ip#1]
while setting up caQtDM screens for 7-BM, found this to be a problem:
- /APSshare/epics/synApps_5_7/support/ip330-2-7/ip330App/op/ui/Ip330Scan.ui, macro: P=7bma1:,R=IP330_
- /APSshare/epics/synApps_5_8/support/ip330-2-8/ip330App/op/ui/Ip330Scan.ui, macro: P=7bmb1:,R=IP330_
- bounding box on title is too small
- in the .adl file, widen the box to span the width of the top row and center the value
- reconvert to various formats
- copy revised .ui file to /APSshare

**Comment by keenanlang** [comment]
This is for the IP330 module. I put in a pull request there.

https://github.com/epics-modules/ip330/pull/4
